spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=${DB_DRIVER}
spring.jpa.hibernate.ddl-auto=validate

server.address=0.0.0.0
server.port=8080
server.forward-headers-strategy=framework
server.tomcat.use-relative-redirects=true